[package]
name = "arg_parser"
version = "0.1.0"
authors = ["Jose Narvaez <goyox86@gmail.com>"]
description = "RedoxOS command line argument parser"
license = "MIT"
repository = "https://gitlab.redox-os.org/redox-os/arg-parser"

[dependencies]
